import turtle
raymond=turtle.Turtle()
raymond.color("red")
raymond.shape("turtle")
raymond.forward(100)
raymond.left(100)
raymond.forward(100)
wilson=turtle.Turtle()
wilson.color("green")
wilson.shape("turtle")
wilson.backward(100)
wilson.right(100)
wilson.forward(100)
raymond.speed(0)
wilson.speed(0)